import { ResultCardData } from './types';

export const RESULT_CARDS: ResultCardData[] = [
  {
    id: 1,
    name: 'Sandeep',
    role: 'Software Engineer, Seattle',
    image: 'https://raw.githubusercontent.com/scale100million-prog/my-images/main/Sandeep%20%20(1).jpg',
    imageAlt: 'Sandeep before and after transformation',
    weekEndLabel: 'WEEK 20',
    resultLine: '16 KG Lost in 20 Weeks',
    before: 'Heaviest he had ever been. Testosterone at 240. Hormonal imbalance. Had tried and failed multiple times.',
    after: 'Lost 16 KG in 20 weeks. Testosterone went from 240 to 478. Same job. Same schedule. Different system.',
  },
  {
    id: 2,
    name: 'Naushad',
    role: 'CTO, Bangalore',
    image: 'https://raw.githubusercontent.com/scale100million-prog/my-images/main/Naushad%202.jpg',
    imageAlt: 'Naushad before and after transformation',
    weekEndLabel: 'WEEK 8',
    resultLine: '9 KG Lost in 8 Weeks',
    before: 'Travelling almost every week. Completely sedentary. No routine that ever survived more than two weeks.',
    after: 'Lost 9 KG and gained 5 KG of muscle in 8 weeks. Results came while travelling almost every week.',
  },
  {
    id: 3,
    name: 'Manoj',
    role: 'Lawyer, Chennai',
    image: 'https://raw.githubusercontent.com/scale100million-prog/my-images/main/Manoj%203.jpg',
    imageAlt: 'Manoj before and after transformation',
    weekEndLabel: 'WEEK 10',
    resultLine: '10 KG Lost in 10 Weeks',
    before: 'Ate out for every single meal. Did not cook once during the programme. Stressful schedule with no room for anything.',
    after: 'Lost 10 KG in 10 weeks. Without cooking a single meal.',
  },
  {
    id: 4,
    name: 'Pradeep',
    role: 'VP at MNC, Florida',
    image: 'https://raw.githubusercontent.com/scale100million-prog/my-images/main/Pradeep%204.jpg',
    imageAlt: 'Pradeep before and after transformation',
    weekEndLabel: 'WEEK 10',
    resultLine: '10 KG Lost in 10 Weeks',
    before: 'High stress. Unplanned travel. No stable routine at any point.',
    after: 'Lost 10 KG in 10 weeks. While nothing on his schedule changed.',
  },
  {
    id: 5,
    name: 'Vinay',
    role: 'Banker, Bangalore',
    image: 'https://raw.githubusercontent.com/scale100million-prog/my-images/main/Vinay%205.jpg',
    imageAlt: 'Vinay before and after transformation',
    weekEndLabel: 'WEEK 12',
    resultLine: '11 KG Lost in 12 Weeks',
    before: 'High stress. Frequent travel. Every previous attempt stopped by the same two things.',
    after: 'Lost 11 KG in 12 weeks.',
  },
  {
    id: 6,
    name: 'Keerthi',
    role: 'Hyderabad',
    image: 'https://raw.githubusercontent.com/scale100million-prog/my-images/main/Keerthi%206.jpg',
    imageAlt: 'Keerthi before and after transformation',
    weekEndLabel: 'WEEK 18',
    resultLine: '19 KG Lost in 18 Weeks',
    before: 'Vegetarian. Completely sedentary. No fitness experience of any kind.',
    after: 'Lost 19 KG in 18 weeks.',
  },
];
